---
functional:
  - Регистрация и аутентификация пользователей
  
  - Создание и управление соревнованиями (администраторами или пользователями, в зависимости от возможностей)

  - Участие в соревнованиях (присоединение к битве, отправка решений, просмотр результатов)

  - Редактор кода с поддержкой нескольких языков программирования

  - Система тестирования решений (запуск кода против тестов)

  - Рейтинги и статистика (личная и общая)

  - Уведомления о начале соревнований, результатах и т.д.

  - Чат или обсуждение задач

  - Поддержка различных типов соревнований (индивидуальные, командные, тренировочные)

non-functional:
  - Система должна быстро компилировать и запускать код, отклик интерфейса

  - возможность обслуживать много одновременных пользователей во время соревнований

  - система должна быть устойчива к ошибкам, особенно при запуске непроверенного кода

  - изоляция выполнения кода (песочница), защита от вредоносного кода, безопасность данных

  - интуитивный интерфейс, понятные инструкции

  - работа в разных браузерах и на разных устройствах

  - Поддержка множества языков программирования и их версий
 
implicit:
  - защита от читерства, списывания

  - Качественные и интересные задачи

  - Оперативная техническая поддержка

  - регулярное обновление задач, поддержка новых языков программирования

  - возможность общаться, делиться решениями, учиться
  
